### ISSUE TITLE
ar71xx_board_name not found

### ISSUE THREAD

**Issue by SteveAyre** [devolo/dlan-openwrt#2]
The plc init.d script fails to start in OpenWRT 18.06 with the following error:

`root@OpenWrt:/etc/config# /etc/init.d/plc start
/etc/rc.common: /etc/init.d/plc: line 14: ar71xx_board_name: not found
/etc/rc.common: .: line 16: can't open '/lib/firmware/plc//fwconfig': No such file or directory
`

The cause is this commit: http://lists.infradead.org/pipermail/lede-commits/2017-December/005265.html which removed the board-specific board name functions and replaced them with a generic one.

The script should now call board_name() which will return the content of /tmp/sysinfo/board_name which is `dlan-pro-1200-ac`

**Comment by dvlemplgk** [comment]
Fixed.

**Comment by SteveAyre** [comment]
Thanks.

This also affects plc-reset and 01_plc.

**Comment by dvlemplgk** [comment]
Thanks for hint. Reworked all three scripts.
